.\"
.\" Kristall man page
.\"
.
.TH KRISTALL 1 $(DATE) Unix "User manuals"
.SH NAME
.PP
.B kristall
\- a cross-platform graphical small-internet client.
.
.SH SYNOPSIS
.B kristall
[\fI\,FLAGS\/\fR]... [\fI\,URL\/\fR]
.
.SH DESCRIPTION
.P
.B kristall
is a small-Internet browser primarily designed for browsing geminispace, but also supports gopher, finger, and basic HTTP/S.
It tries to fill the hole of graphical browsers for these alternative Internet protocols, with a high usability, feature richness, and somewhat familiar interface for newcomers.
.
.SH FLAGS
.TP
\fB\-h\fR, \fB\-\-help\fR
Displays help information
.
.TP
\fB\-v\fR, \fB\-\-version\fR
Displays version information
.
.TP
\fB\-w\fR, \fB\-\-new-window\fR
Opens \fIURL\fR in a new window if another Kristall session is already running (instead of opening a new tab).
.
.TP
\fB\-i\fR, \fB\-\-isolated\fR
Starts the instance of Kristall as an isolated session that cannot communicate with other Kristall windows.
.
.\" Stuff after this is converted from the Gemtext about:help file
